# Exploring airport codes data

In [2]:
!pip3 install datapackage

Collecting datapackage
  Downloading https://files.pythonhosted.org/packages/53/f3/d70f2f7dcb9883e586fa54f3937b9281242bde7751ed3162b4cdb047240e/datapackage-1.15.2-py2.py3-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 5.7MB/s ta 0:00:011
Requirement already satisfied: requests>=2.8 in /opt/conda/lib/python3.6/site-packages (from datapackage) (2.18.4)
Requirement already satisfied: click>=6.7 in /opt/conda/lib/python3.6/site-packages (from datapackage) (6.7)
Collecting jsonpointer>=1.10 (from datapackage)
  Downloading https://files.pythonhosted.org/packages/23/52/05f67532aa922e494c351344e0d9624a01f74f5dd8402fe0d1b563a6e6fc/jsonpointer-2.1-py2.py3-none-any.whl
Collecting unicodecsv>=0.14 (from datapackage)
  Downloading https://files.pythonhosted.org/packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz
Requirement already satisfied: six>=1.10 in /opt/conda/lib/python3.6/site-packages (from datapackage) (1.11.0)
Collecting tableschema>=1.12.1 (from datapackage)
  Downloading https://files.pythonhosted.org/packages/45/16/4ef6cb5315b8e9fcf124cc914ac1920d76f9ac25859d3a2eeee3e329ae31/tableschema-1.20.2-py2.py3-none-any.whl (68kB)
    100% |████████████████████████████████| 71kB 10.9MB/s ta 0:00:01
Collecting tabulator>=1.29 (from datapackage)
  Downloading https://files.pythonhosted.org/packages/d2/ac/7eabdc64f583306712d68a219a0feb4efe11a0f31022ee08d3dc7d849759/tabulator-1.53.5-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 12.6MB/s ta 0:00:01
Requirement already satisfied: chardet>=3.0 in /opt/conda/lib/python3.6/site-packages (from datapackage) (3.0.4)
Requirement already satisfied: jsonschema>=2.5 in /opt/conda/lib/python3.6/site-packages (from datapackage) (2.6.0)
Requirement already satisfied: idna<2.7,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests>=2.8->datapackage) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests>=2.8->datapackage) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests>=2.8->datapackage) (2019.11.28)
Collecting isodate>=0.5.4 (from tableschema>=1.12.1->datapackage)
  Downloading https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 12.3MB/s ta 0:00:01
Requirement already satisfied: python-dateutil>=2.4 in /opt/conda/lib/python3.6/site-packages (from tableschema>=1.12.1->datapackage) (2.6.1)
Collecting rfc3986>=1.1.0 (from tableschema>=1.12.1->datapackage)
  Downloading https://files.pythonhosted.org/packages/c4/e5/63ca2c4edf4e00657584608bee1001302bbf8c5f569340b78304f2f446cb/rfc3986-1.5.0-py2.py3-none-any.whl
Collecting cached-property>=1.5 (from tableschema>=1.12.1->datapackage)
  Downloading https://files.pythonhosted.org/packages/48/19/f2090f7dad41e225c7f2326e4cfe6fff49e57dedb5b53636c9551f86b069/cached_property-1.5.2-py2.py3-none-any.whl
Requirement already satisfied: sqlalchemy>=0.9.6 in /opt/conda/lib/python3.6/site-packages (from tabulator>=1.29->datapackage) (1.1.13)
Collecting linear-tsv>=1.0 (from tabulator>=1.29->datapackage)
  Downloading https://files.pythonhosted.org/packages/82/e5/03207a0f11e1d60df85b97b61704ed701b725a7c2feaf83f7bfbd0c2d83e/linear-tsv-1.1.0.tar.gz
Requirement already satisfied: xlrd>=1.0 in /opt/conda/lib/python3.6/site-packages (from tabulator>=1.29->datapackage) (1.1.0)
Collecting openpyxl>=2.6 (from tabulator>=1.29->datapackage)
  Downloading https://files.pythonhosted.org/packages/39/08/595298c9b7ced75e7d23be3e7596459980d63bc35112ca765ceccafbe9a4/openpyxl-3.0.7-py2.py3-none-any.whl (243kB)
    100% |████████████████████████████████| 245kB 9.3MB/s eta 0:00:01
Collecting jsonlines>=1.1 (from tabulator>=1.29->datapackage)
  Downloading https://files.pythonhosted.org/packages/d4/58/06f430ff7607a2929f80f07bfd820acbc508a4e977542fefcc522cde9dff/jsonlines-2.0.0-py3-none-any.whl
Collecting ijson>=3.0.3 (from tabulator>=1.29->datapackage)
  Downloading https://files.pythonhosted.org/packages/89/ff/5c908dbbdcb8387d11632904af0f9b60b8508a2655070a0baf511f0cec06/ijson-3.1.4-cp36-cp36m-manylinux1_x86_64.whl (124kB)
    100% |████████████████████████████████| 133kB 18.7MB/s ta 0:00:01
Requirement already satisfied: boto3>=1.9 in /opt/conda/lib/python3.6/site-packages (from tabulator>=1.29->datapackage) (1.9.7)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.6/site-packages (from openpyxl>=2.6->tabulator>=1.29->datapackage) (1.0.1)
Requirement already satisfied: botocore<1.13.0,>=1.12.7 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9->tabulator>=1.29->datapackage) (1.12.7)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9->tabulator>=1.29->datapackage) (0.9.3)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /opt/conda/lib/python3.6/site-packages (from boto3>=1.9->tabulator>=1.29->datapackage) (0.1.13)
Requirement already satisfied: docutils>=0.10 in /opt/conda/lib/python3.6/site-packages (from botocore<1.13.0,>=1.12.7->boto3>=1.9->tabulator>=1.29->datapackage) (0.14)
Building wheels for collected packages: unicodecsv, linear-tsv
  Running setup.py bdist_wheel for unicodecsv ... done
  Stored in directory: /root/.cache/pip/wheels/a6/09/e9/e800279c98a0a8c94543f3de6c8a562f60e51363ed26e71283
  Running setup.py bdist_wheel for linear-tsv ... done
  Stored in directory: /root/.cache/pip/wheels/3f/8a/cb/38917fd1ef4356b9870ace7331b83417dc594bf2c029bd991f
Successfully built unicodecsv linear-tsv
Installing collected packages: jsonpointer, unicodecsv, isodate, rfc3986, cached-property, linear-tsv, openpyxl, jsonlines, ijson, tabulator, tableschema, datapackage
  Found existing installation: openpyxl 2.5.0b1
    Uninstalling openpyxl-2.5.0b1:
      Successfully uninstalled openpyxl-2.5.0b1
Successfully installed cached-property-1.5.2 datapackage-1.15.2 ijson-3.1.4 isodate-0.6.0 jsonlines-2.0.0 jsonpointer-2.1 linear-tsv-1.1.0 openpyxl-3.0.7 rfc3986-1.5.0 tableschema-1.20.2 tabulator-1.53.5 unicodecsv-0.14.1

In [3]:
# Do all imports and installs here
import pandas as pd
from datapackage import Package

In [4]:
data_url = 'https://datahub.io/core/airport-codes/datapackage.json'

# to load Data Package into storage
package = Package(data_url)

# to load only tabular data
resources = package.resources
for resource in resources:
    print(resource.descriptor['path'])

https://pkgstore.datahub.io/core/airport-codes/validation_report/data/b6cc32a916f988746d20b52925d82774/validation_report.json
https://pkgstore.datahub.io/core/airport-codes/airport-codes_csv/data/e07739e49300d125989ee543d5598c4b/airport-codes_csv.csv
https://pkgstore.datahub.io/core/airport-codes/airport-codes_json/data/9ca22195b4c64a562a0a8be8d133e700/airport-codes_json.json
https://pkgstore.datahub.io/core/airport-codes/airport-codes_zip/data/173bf3d453e2aea540dc01c3421753fe/airport-codes_zip.zip
https://pkgstore.datahub.io/core/airport-codes/airport-codes_csv_preview/data/37ec674b229d067da717e49b3715d1ce/airport-codes_csv_preview.json
https://pkgstore.datahub.io/core/airport-codes/airport-codes/archive/dfadb79d7ba34a49242332f2eaf4f1b0/airport-codes.csv

In [5]:
data1 = pd.read_csv(package.resources[1].descriptor['path'])
data1.shape

(57421, 12)

In [6]:
data5 = pd.read_csv(package.resources[5].descriptor['path'])
data5.shape

(57421, 12)

different resource doesn't seem to have much difference, i'll use the _csv

In [7]:
#let's see what it looks like
raw_airportcode = data1
raw_airportcode.head()

,ident,type,name,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code,coordinates
0,00A,heliport,Total Rf Heliport,11.0,NaN,US,US-PA,Bensalem,00A,NaN,00A,"-74.93360137939453, 40.07080078125"
1,00AA,small_airport,Aero B Ranch Airport,3435.0,NaN,US,US-KS,Leoti,00AA,NaN,00AA,"-101.473911, 38.704022"
2,00AK,small_airport,Lowell Field,450.0,NaN,US,US-AK,Anchor Point,00AK,NaN,00AK,"-151.695999146, 59.94919968"
3,00AL,small_airport,Epps Airpark,820.0,NaN,US,US-AL,Harvest,00AL,NaN,00AL,"-86.77030181884766, 34.86479949951172"
4,00AR,closed,Newport Hospital & Clinic Heliport,237.0,NaN,US,US-AR,Newport,NaN,NaN,NaN,"-91.254898, 35.6087"

In [8]:
#see how many are missing
raw_airportcode.isnull().sum()

ident               0
type                0
name                0
elevation_ft     7813
continent       28443
iso_country       246
iso_region          0
municipality     5894
gps_code        15860
iata_code       48196
local_code      27391
coordinates         0
dtype: int64

In [9]:
# why would municipality be missing? how do we know which city is it then?
raw_airportcode[raw_airportcode['municipality'].isnull()].head()

,ident,type,name,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code,coordinates
1550,15SD,heliport,Watertown / Brownlee Heliport,1720.0,NaN,US,US-SD,NaN,15SD,NaN,NaN,"-97.1080899239, 44.883264878199995"
2459,21ID,heliport,Nordman / Phillabaum Heliport,2440.0,NaN,US,US-ID,NaN,21ID,NaN,NaN,"-116.871174574, 48.631483378700004"
4417,3ME7,seaplane_base,Peru / Destiny Cove SPB,580.0,NaN,US,US-ME,NaN,3ME7,NaN,NaN,"-70.396957, 44.460597"
7690,6XA4,small_airport,Zadow Airstrip,NaN,NaN,US,US-TX,NaN,6XA4,NaN,NaN,"-95.954353809, 29.991738550900003"
7926,74xa,small_airport,Gun Barrel City Airpark,385.0,NaN,US,US-TX,NaN,74XA,NaN,NaN,"-96.1456650496, 32.3551499558"

In [10]:
#is ident unique??
raw_airportcode['ident'].is_unique

True

In [11]:
#see countries with most airports
raw_airportcode.iloc[:,5:7].groupby('iso_country').count().sort_values(by = 'iso_region',ascending = False).head(10)

             iso_region
iso_country
US                23256
BR                 5043
CA                 2794
AU                 2018
MX                 1405
KR                 1374
GB                 1203
RU                 1121
DE                  957
FR                  893

In [12]:
#what iso_region is like for non US airports??
raw_airportcode[raw_airportcode['iso_country']=='CA'].head()

,ident,type,name,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code,coordinates
13656,CA-0001,closed,Lac-des-Loups Airport,NaN,NaN,CA,CA-QC,Lac-des-Loups,NaN,NaN,NaN,"-76.48249816894531, 46.982200622558594"
13657,CA-0002,small_airport,Pourvoirie Joncas Airstrip,NaN,NaN,CA,CA-QC,Saint-Lazare,NaN,NaN,NaN,"-77.631103515625, 47.10540008544922"
13658,CA-0003,closed,RCAF Station Buttress,NaN,NaN,CA,CA-SK,Moose Jaw,NaN,NaN,NaN,"-105.5479965209961, 50.23609924316406"
13659,CA-0004,closed,RCAF Station Aylmer,NaN,NaN,CA,CA-ON,Aylmer,NaN,NaN,NaN,"-80.94419860839844, 42.80590057373047"
13660,CA-0005,closed,RCAF Station Lincoln Park,NaN,NaN,CA,CA-AB,Calgary,NaN,NaN,NaN,"-114.13300323486328, 51.0093994140625"

In [13]:
#check Chinese airports as i'm more familiar witht the names
raw_airportcode[raw_airportcode['iso_country']=='CN'].head()

,ident,type,name,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code,coordinates
10459,AEQ,small_airport,Ar Horqin Airport,1335.0,AS,CN,CN-15,Chifeng,NaN,AEQ,NaN,"120.15958, 43.87042"
10516,AHJ,medium_airport,Hongyuan Airport,11600.0,AS,CN,CN-51,Aba,ZUHY,AHJ,NaN,"102.35224, 32.53154"
11775,AXF,medium_airport,Alxa Left Banner Bayanhot Airport,4560.0,AS,CN,CN-15,Bayanhot,ZBAL,AXF,NaN,"105.58858, 38.74831"
15804,CN-0001,closed,Old Guangzhou Baiyun International Airport,NaN,AS,CN,CN-44,Guangzhou,NaN,NaN,NaN,"113.26599884033203, 23.184200286865234"
15805,CN-0002,medium_airport,Nanjing Air Base,NaN,AS,CN,CN-32,Nanjing,NaN,NaN,NaN,"118.81199645996094, 31.998300552368164"

In [14]:
#I don't see much changes we need
airportcode = raw_airportcode

In [15]:
airportcode.head()

,ident,type,name,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code,coordinates
0,00A,heliport,Total Rf Heliport,11.0,NaN,US,US-PA,Bensalem,00A,NaN,00A,"-74.93360137939453, 40.07080078125"
1,00AA,small_airport,Aero B Ranch Airport,3435.0,NaN,US,US-KS,Leoti,00AA,NaN,00AA,"-101.473911, 38.704022"
2,00AK,small_airport,Lowell Field,450.0,NaN,US,US-AK,Anchor Point,00AK,NaN,00AK,"-151.695999146, 59.94919968"
3,00AL,small_airport,Epps Airpark,820.0,NaN,US,US-AL,Harvest,00AL,NaN,00AL,"-86.77030181884766, 34.86479949951172"
4,00AR,closed,Newport Hospital & Clinic Heliport,237.0,NaN,US,US-AR,Newport,NaN,NaN,NaN,"-91.254898, 35.6087"

In [16]:
# create a separate region column
airportcode = airportcode.assign(iso_region2 = lambda x: x['iso_region'].str.split('-',1).str[-1])

In [17]:
# create separate lat log
airportcode[['lat','lon']] = airportcode['coordinates'].str.split(',',1,expand = True)

In [18]:
airportcode.head()

,ident,type,name,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code,coordinates,iso_region2,lat,lon
0,00A,heliport,Total Rf Heliport,11.0,NaN,US,US-PA,Bensalem,00A,NaN,00A,"-74.93360137939453, 40.07080078125",PA,-74.93360137939453,40.07080078125
1,00AA,small_airport,Aero B Ranch Airport,3435.0,NaN,US,US-KS,Leoti,00AA,NaN,00AA,"-101.473911, 38.704022",KS,-101.473911,38.704022
2,00AK,small_airport,Lowell Field,450.0,NaN,US,US-AK,Anchor Point,00AK,NaN,00AK,"-151.695999146, 59.94919968",AK,-151.695999146,59.94919968
3,00AL,small_airport,Epps Airpark,820.0,NaN,US,US-AL,Harvest,00AL,NaN,00AL,"-86.77030181884766, 34.86479949951172",AL,-86.77030181884766,34.86479949951172
4,00AR,closed,Newport Hospital & Clinic Heliport,237.0,NaN,US,US-AR,Newport,NaN,NaN,NaN,"-91.254898, 35.6087",AR,-91.254898,35.6087

In [19]:
airportcode.to_csv('dataoutput/airportcode.csv',index = False)